import * as IMAGES from "../images/control_icons";

type Control = {
  shortName: string;
  name: string;
  image: string;
};

export const CONTROLS: Record<string, Control | undefined> = {
  0: { shortName: "0", name: "0 Key", image: IMAGES.control_0 },
  1: { shortName: "1", name: "1 Key", image: IMAGES.control_1 },
  2: { shortName: "2", name: "2 Key", image: IMAGES.control_2 },
  3: { shortName: "3", name: "3 Key", image: IMAGES.control_3 },
  4: { shortName: "4", name: "4 Key", image: IMAGES.control_4 },
  5: { shortName: "5", name: "5 Key", image: IMAGES.control_5 },
  6: { shortName: "6", name: "6 Key", image: IMAGES.control_6 },
  7: { shortName: "7", name: "7 Key", image: IMAGES.control_7 },
  8: { shortName: "8", name: "8 Key", image: IMAGES.control_8 },
  9: { shortName: "9", name: "9 Key", image: IMAGES.control_9 },
  ALT: { shortName: "alt", name: "Alt", image: IMAGES.control_alt },
  A: { shortName: "a", name: "A Key", image: IMAGES.control_a },
  B: { shortName: "b", name: "B Key", image: IMAGES.control_b },
  BACKSPACE: {
    shortName: "backspace",
    name: "Backspace",
    image: IMAGES.control_backspace,
  },
  C: { shortName: "c", name: "C Key", image: IMAGES.control_c },
  CAPS_LOCK: { shortName: "caps", name: "Caps", image: IMAGES.control_caps },
  COMMA: { shortName: "comma", name: "Comma", image: IMAGES.control_comma },
  CONTROL: { shortName: "ctrl", name: "Ctrl", image: IMAGES.control_ctrl },
  D: { shortName: "d", name: "D Key", image: IMAGES.control_d },
  DASH: { shortName: "dash", name: "Dash", image: IMAGES.control_dash },
  DEL: { shortName: "del", name: "Delete", image: IMAGES.control_del },
  DOWN: {
    shortName: "down",
    name: "Down",
    image: IMAGES.control_down,
  },
  E: { shortName: "e", name: "E Key", image: IMAGES.control_e },
  ENTER: { shortName: "enter", name: "Enter", image: IMAGES.control_enter },
  EQUALS: {
    shortName: "equal",
    name: "Equal",
    image: IMAGES.control_equal,
  },
  ESCAPE: { shortName: "esc", name: "Esc", image: IMAGES.control_esc },
  F: { shortName: "f", name: "F Key", image: IMAGES.control_f },
  F1: { shortName: "f1", name: "F1", image: IMAGES.control_f1 },
  F2: { shortName: "f2", name: "F2", image: IMAGES.control_f2 },
  F3: { shortName: "f3", name: "F3", image: IMAGES.control_f3 },
  F4: { shortName: "f4", name: "F4", image: IMAGES.control_f4 },
  F5: { shortName: "f5", name: "F5", image: IMAGES.control_f5 },
  F6: { shortName: "f6", name: "F6", image: IMAGES.control_f6 },
  F7: { shortName: "f7", name: "F7", image: IMAGES.control_f7 },
  F8: { shortName: "f8", name: "F8", image: IMAGES.control_f8 },
  F9: { shortName: "f9", name: "F9", image: IMAGES.control_f9 },
  F10: { shortName: "f10", name: "F10", image: IMAGES.control_f10 },
  F11: { shortName: "f11", name: "F11", image: IMAGES.control_f11 },
  F12: { shortName: "f12", name: "F12", image: IMAGES.control_f12 },
  BACKTICK: {
    shortName: "backtick",
    name: "Backtick",
    image: IMAGES.control_backtick,
  },
  G: { shortName: "g", name: "G Key", image: IMAGES.control_g },
  H: { shortName: "h", name: "H Key", image: IMAGES.control_h },
  I: { shortName: "i", name: "I Key", image: IMAGES.control_i },
  J: { shortName: "j", name: "J Key", image: IMAGES.control_j },
  K: { shortName: "k", name: "K Key", image: IMAGES.control_k },
  L: { shortName: "l", name: "L Key", image: IMAGES.control_l },
  LEFT: {
    shortName: "left",
    name: "Left",
    image: IMAGES.control_left,
  },
  LEFT_MOUSE: {
    shortName: "lmouse",
    name: "Lmouse",
    image: IMAGES.control_lmouse,
  },
  LEFT_SHIFT: {
    shortName: "lshift",
    name: "Lshift",
    image: IMAGES.control_shift,
  },
  LEFT_SLASH: {
    shortName: "lslash",
    name: "Lslash",
    image: IMAGES.control_lslash,
  },
  LEFT_SQUARE_BRACKET: {
    shortName: "lsquarebraket",
    name: "Lsquarebraket",
    image: IMAGES.control_lsquarebraket,
  },
  M: { shortName: "m", name: "M Key", image: IMAGES.control_m },
  MENU: {
    shortName: "menu",
    name: "Menu",
    image: IMAGES.control_menu,
  },
  MOUSE: { shortName: "mouse", name: "Mouse", image: IMAGES.control_mouse },
  N: { shortName: "n", name: "N Key", image: IMAGES.control_n },
  O: { shortName: "o", name: "O Key", image: IMAGES.control_o },
  P: { shortName: "p", name: "P Key", image: IMAGES.control_p },
  PERIOD: {
    shortName: "period",
    name: "Period",
    image: IMAGES.control_period,
  },
  Q: { shortName: "q", name: "Q Key", image: IMAGES.control_q },
  QUOTE: { shortName: "quote", name: "Quote", image: IMAGES.control_quote },
  R: { shortName: "r", name: "R Key", image: IMAGES.control_r },
  RIGHT: {
    shortName: "right",
    name: "Right",
    image: IMAGES.control_right,
  },
  RIGHT_MOUSE: {
    shortName: "rmouse",
    name: "Rmouse",
    image: IMAGES.control_rmouse,
  },

  RIGHT_SHIFT: {
    shortName: "rshift",
    name: "Rshift",
    image: IMAGES.control_rshift,
  },
  RIGHT_SLASH: {
    shortName: "rslash",
    name: "Rslash",
    image: IMAGES.control_rslash,
  },
  RIGHT_SQUARE_BRACKET: {
    shortName: "rsquarebraket",
    name: "Rsquarebraket",
    image: IMAGES.control_rsquarebraket,
  },
  S: { shortName: "s", name: "S Key", image: IMAGES.control_s },
  SEMICOLON: {
    shortName: "semicolon",
    name: "Semicolon",
    image: IMAGES.control_semicolon,
  },
  SHIFT: { shortName: "shift", name: "Shift", image: IMAGES.control_shift },
  SPACE: { shortName: "space", name: "Space", image: IMAGES.control_space },
  T: { shortName: "t", name: "T Key", image: IMAGES.control_t },
  TAB: { shortName: "tab", name: "Tab", image: IMAGES.control_tab },
  U: { shortName: "u", name: "U Key", image: IMAGES.control_u },
  UP: { shortName: "up", name: "Up", image: IMAGES.control_up },
  V: { shortName: "v", name: "V Key", image: IMAGES.control_v },
  W: { shortName: "w", name: "W Key", image: IMAGES.control_w },
  WASD: { shortName: "wasd", name: "Wasd", image: IMAGES.control_wasd },
  X: { shortName: "x", name: "X Key", image: IMAGES.control_x },
  Y: { shortName: "y", name: "Y Key", image: IMAGES.control_y },
  Z: { shortName: "z", name: "Z Key", image: IMAGES.control_z },
  ARROW_KEYS: {
    shortName: "arrowkeys",
    name: "Arrow Keys",
    image: IMAGES.control_arrowkeys,
  },
};
